# Generated by Django 4.2.15 on 2024-08-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('follower', 'Follower')], default='follower', max_length=15),
        ),
    ]
